name             'sample-app'
maintainer       'Zachary Danger Campbell'
maintainer_email 'zacharydangercampbell@gmail.com'
license          'MIT'
description      'Installs/Configures sample-app'
long_description 'Installs/Configures sample-app'
version          '0.1.0'

depends 'apt'
depends 'postgresql'
depends 'database'
depends 'nginx'
depends 'user'
depends 'redisio'
depends 'rvm'
depends 'runit'
